In [1]:
import pandas as pd


In [2]:
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

,area,bedrooms,age,price
0,2600,3,20,550000
1,3000,4,15,565000
2,3200,4,18,610000
3,3600,3,30,595000
4,4000,5,8,760000
5,4100,6,8,810000


In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [6]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
model.intercept_

np.float64(221323.0018654043)

In [10]:
model.predict([[5000,3,12]])

C:\Users\anujs\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([813021.2369063])

# Save model to file using pickle

In [11]:
import pickle

In [14]:
with open('model_pickle','wb') as f:
    mp = pickle.dump(model,f)

In [15]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

# load saved model

In [16]:
mp.predict([[5000,3,12]])

C:\Users\anujs\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([813021.2369063])

# Save Trained Model using joblib

In [20]:
import joblib

In [21]:
joblib.dump(model,'model_joblib')

['model_joblib']

# Load model using joblib

In [22]:
mj = joblib.load('model_joblib')

In [23]:
mj.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [24]:
mj.intercept_

np.float64(221323.0018654043)

In [25]:
mj.predict([[5000,3,12]])

C:\Users\anujs\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([813021.2369063])